#!/bin/bash
# Autor: Francisco Dias
# Data de criação: 18/05/2020
# Data de atualização: 18/05/2020
# Versão: 0.01
# Testado e homologado para a versão do Ubuntu Server 16.04 LTS x64
# Kernel >= 4.4.x
#
# Criando as váriaveis de validação do diretório
LOG="/var/log/samba/log.limpeza_pdf"
PDF="/arquivos/ti-pro.intra/pdf"

#Acessando o diretório
cd $PDF
LOCAL="`pwd`"

#Fazendo o teste lógico para a limpeza do diretório PDF.
if [ $PDF == $LOCAL ]; then
	echo -e "Fazendo a limpeza do diretório: $PDF em: `date`" > $LOG
	echo >> $LOG
	  rm -Rfv * >> $LOG
	echo >> $LOG
	echo -e "Pasta PDF limpa com sucesso!!!" >> $LOG
else
	echo -e "Diretório $PDF inexistente, verificar as configurações da váriavél de ambiente, localização dos arquivos, etc" >> $LOG
fi
